### ISSUE TITLE
[Bug]: Can't active the chunk loader (NEOFORGE)

### ISSUE THREAD

**Issue by poziel** [Mrbysco/Chunky-McChunkFace#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

21.0.63-beta

### Minecraft version

1.21

### Mod version

Chunky McChunkFace 1.21

### Java version

JRE 1.8.0_391

### Issue Description

I've tried everything to activate the chunk loader, but I just can't seems to activate it. I hope I'm not crazy, but the intended method to activate it seems to be right-click, but it does nothing on my end.

**Comment by Mrbysco** [comment]
It's been fixed and a new version is being uploaded and will be available shortly. Thanks for reporting the issue

**Comment by poziel** [comment]
Thanks for your speed 👍
